# Generated by Django 4.1.9 on 2023-09-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kerelem',
            name='felvett',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kerelem',
            name='torlesztett',
            field=models.BooleanField(default=False),
        ),
    ]
