# Generated by Django 4.1.9 on 2023-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_database', '0002_alter_kerelem_felvett_alter_kerelem_torlesztett'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzakcio',
            name='datatime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
